/**
 * Materialize the rest of lib/ from this file (the only tracked file under lib/).
 * Other lib/ paths are gitignored so branch switches share the same local tooling.
 *
 * Edit the FILES map below, then run: npm run bootstrap
 */

const fs = require("fs");
const path = require("path");

const libRoot = path.join(__dirname, "..");

const FILES = {
	"config/env.js": `require("dotenv").config();

function num(v, fallback) {
	var x = Number(v);
	return Number.isFinite(x) ? x : fallback;
}

var fromEnv = Object.assign({}, process.env);

module.exports = Object.assign(fromEnv, {
	PORT_PROJECT: num(fromEnv.PORT_PROJECT, 3301),
	RUN_PROJECT: fromEnv.RUN_PROJECT !== "false" && fromEnv.RUN_PROJECT !== "0",
});
`,

	"config/webpack.config.js": `const path = require("path");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
	entry: "./project/src/index.js",
	output: {
		path: path.resolve(__dirname, "../../dist"),
		filename: "bundle.js",
		clean: true,
	},
	module: {
		rules: [
			{
				test: /\\.css$/i,
				use: ["style-loader", "css-loader"],
			},
		],
	},

	// do not minify js code
	optimization: {
		minimize: false,
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: "./project/public/index.html",
			inject: "body",
			publicPath: "./",
			minify: false,
		}),
	],
};
`,

	"config/webpack.config.dev.js": `const path = require("path");
const config = require("./webpack.config");
const env = require("./env");
const {createBranchArtworkSaver} = require("../../project/public/library/node/branchArtworkSaver");

module.exports = {
	...config,
	mode: "development",
	devServer: {
		// disables the Hot Module Replacement feature because probably not ideal
		// in the context of generative art
		// https://webpack.js.org/concepts/hot-module-replacement/
		hot: false,
		port: env.PORT_PROJECT,
		host: "0.0.0.0", // Allow access from other devices on your network
		// server resources from the public folder, located in /project
		static: {
			directory: path.join(__dirname, "..", "..", "project", "public"),
		},
		client: {
			overlay: {
				errors: true,
				warnings: false,
			},
		},
		setupMiddlewares: (middlewares, devServer) => {
			devServer.app.use(
				createBranchArtworkSaver({
					repoRoot: path.join(__dirname, "..", ".."),
				}),
			);
			return middlewares;
		},
	},
	plugins: [...config.plugins],
};
`,

	"config/webpack.config.prod.js": `const CopyPlugin = require("copy-webpack-plugin");
const config = require("./webpack.config");
const ZipperPlugin = require("./ZipperPlugin");
const path = require("path");

module.exports = {
	...config,
	mode: "production",
	// add the zipper plugin to the list of plugins
	plugins: [
		...config.plugins,
		new CopyPlugin({
			patterns: [
				{
					from: "./project/public",
					// prevents the index.html from being copied to the the public folder, as it's going to be
					// generated by webpack
					filter: async (filePath) => {
						if (path.basename(filePath) === "index.html") return false;
						if (filePath.includes(\`\${path.sep}.git\${path.sep}\`)) return false;
						return true;
					},
				},
			],
		}),
		new ZipperPlugin(),
	],
};
`,

	"config/ZipperPlugin.js": `const path = require("path")
const AdmZip = require("adm-zip")


const defaultOptions = {
  outputPath: path.resolve(__dirname, "../../dist-zipped/project.zip")
}

/**
 * The zipper plugin hooks to the end of compilation event, and it creates a ZIP file of
 * all the files within the ./dist folder into the ./dist-zipped folder to create a distributable zip.
 * https://webpack.js.org/contribute/writing-a-plugin/
 */
class ZipperPlugin {
  constructor(options = {}) {
    this.options = {
      ...defaultOptions,
      ...options
    }
  }

  apply(compiler) {
    // Specify the event hook to attach to
    compiler.hooks.done.tapAsync(
      "ZipperPlugin",
      (stats, callback) => {
        const outputPath = stats.compilation.outputOptions.path
        const zip = new AdmZip()
        zip.addLocalFolder(outputPath)
        zip.toBuffer()
        zip.writeZip(this.options.outputPath)
        callback()
      }
    )
  }
}

module.exports = ZipperPlugin
`,

	"scripts/start.js": `/**
 * Starts webpack-dev-server for local development with live reload.
 * Opens the project directly at http://localhost:3301 (no fxlens wrapper).
 */

const chalk = require("chalk");
const Webpack = require("webpack");
const WebpackDevServer = require("webpack-dev-server");
const open = require("open");

const env = require("../config/env");
const webpackConfig = require("../config/webpack.config.dev");

const logger = {
	error: chalk.red.bold,
	success: chalk.green.bold,
	url: chalk.bold.blue,
};

function padn(n, len = 2, char = "0") {
	return n.toString().padStart(len, char);
}

(async () => {
	const URL_PROJECT = \`http://localhost:\${env.PORT_PROJECT}\`;

	const compiler = Webpack({
		...webpackConfig,
		infrastructureLogging: {
			level: "error",
		},
		stats: "errors-only",
	});
	const server = new WebpackDevServer(webpackConfig.devServer, compiler);

	compiler.hooks.done.tap("project", (stats) => {
		const hasErrors = stats.hasErrors();
		if (hasErrors) {
			console.log(logger.error("[project] compilation has failed"));
		} else {
			const date = new Date();
			const time = \`\${padn(date.getHours())}:\${padn(date.getMinutes())}:\${padn(date.getSeconds())}\`;
			console.log(\`\${logger.success("[project] compiled successfully")} @ \${time}\`);
		}
	});

	server.startCallback(() => {
		console.log(\`\${logger.success("[project] your project is running on")} \${logger.url(URL_PROJECT)}\`);
		console.log();
		open(URL_PROJECT).catch(() => {});
	});
})();
`,
};

for (const [rel, content] of Object.entries(FILES)) {
	const dest = path.join(libRoot, rel);
	fs.mkdirSync(path.dirname(dest), {recursive: true});
	fs.writeFileSync(dest, content);
}

console.log("[bootstrap] wrote lib/ tooling from lib/scripts/bootstrap-lib.js");
