name: Deploy on Vercel
on:
  push:
    branches:
      - "wip/sartoro-live"
      - "wip/sartoro-live-wisp"
      - "wip/sartoro-live-wiggle"
jobs:
  Live-Vercel-Hook:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/wip/sartoro-live'}}
    steps:
      - uses: muinmomin/webhook-action@v1.0.0
        with:
          url: https://api.vercel.com/v1/integrations/deploy/prj_buWhFri4fxlm4HbFJfNTheORCS7T/EUEdaROu7O
  Wisp-Vercel-Hook:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/wip/sartoro-live-wisp'}}
    steps:
      - uses: muinmomin/webhook-action@v1.0.0
        with:
          url: https://api.vercel.com/v1/integrations/deploy/prj_buWhFri4fxlm4HbFJfNTheORCS7T/iGnOy5fhSM
  Wiggle-Vercel-Hook:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/wip/sartoro-live-wiggle'}}
    steps:
      - uses: muinmomin/webhook-action@v1.0.0
        with:
          url: https://api.vercel.com/v1/integrations/deploy/prj_buWhFri4fxlm4HbFJfNTheORCS7T/Mpq8yJZGef