name: Deploy on Vercel
on:
  push:
    branches:
      - "wip/sartoro-live"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: muinmomin/webhook-action@v1.0.0
        with:
          url: https://api.vercel.com/v1/integrations/deploy/prj_buWhFri4fxlm4HbFJfNTheORCS7T/EUEdaROu7O